"""Deterministic synthetic ALZ/EGG regression archives, generated by this project.

Uses Python's standard compression libraries and the public format field layouts.
No upstream archive content or third-party source code is copied into these fixtures.
The encrypted fixtures use the public test password: 암호.
"""
import bz2
import lzma
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).parent
U16 = lambda n: struct.pack('<H', n)
U32 = lambda n: struct.pack('<I', n)
U64 = lambda n: struct.pack('<Q', n)
END = U32(0x08E28222)
PAYLOAD = 'ZipLens 한글 압축 테스트\n'.encode()

def crc_byte(crc, b):
    crc ^= b
    for _ in range(8):
        crc = (crc >> 1) ^ (0xEDB88320 if crc & 1 else 0)
    return crc

def encrypt(data, password):
    keys = [0x12345678, 0x23456789, 0x34567890]
    def update(b):
        keys[0] = crc_byte(keys[0], b)
        keys[1] = ((keys[1] + (keys[0] & 255)) * 134775813 + 1) & 0xffffffff
        keys[2] = crc_byte(keys[2], keys[1] >> 24)
    for b in password:
        update(b)
    out = bytearray()
    for b in data:
        temp = keys[2] | 2
        out.append(b ^ ((temp * (temp ^ 1) >> 8) & 255))
        update(b)
    return bytes(out)

def encode(method, data):
    if method == 0:
        return data
    if method == 1:
        c = zlib.compressobj(wbits=-15)
        return c.compress(data) + c.flush()
    if method == 2:
        return bz2.compress(data)
    if method == 3:
        # An AZO stored block still exercises AZO framing and CRC validation.
        return b'\x31\0' + struct.pack('>III', len(data), len(data), 0) + data + bytes(12)
    stream = lzma.compress(data, format=lzma.FORMAT_ALONE,
                           filters=[{'id': lzma.FILTER_LZMA1, 'dict_size': 4096}])
    return bytes(4) + stream[:5] + stream[13:]

def alz_bzip(data):
    bits = ''.join(f'{b:08b}' for b in bz2.compress(data))
    end = bits.index(f'{0x177245385090:048b}', 113)
    bits = f'{0x444C5A01:032b}' + bits[113:end] + f'{0x444C5A02:032b}'
    bits += '0' * (-len(bits) % 8)
    return int(bits, 2).to_bytes(len(bits) // 8, 'big')

def alz_file(name, data, method=0, password=False):
    name = name.encode('cp949')
    packed = alz_bzip(data) if method == 1 else encode(1 if method == 2 else 0, data)
    crc = zlib.crc32(data)
    verify = b''
    if password:
        cipher = encrypt(bytes(11) + bytes([crc >> 24]) + packed, '암호'.encode('cp949'))
        verify, packed = cipher[:12], cipher[12:]
    return (b'BLZ\x01' + U16(len(name)) + bytes([0]) + bytes(4)
            + bytes([0x40 | int(password), 0, method, 0]) + U32(crc)
            + U32(len(packed)) + U32(len(data)) + name + verify + packed)

def alz(method=0, password=False):
    return (b'ALZ\x01' + bytes(4)
            + alz_file('폴더/한글.txt', PAYLOAD, method, password)
            + alz_file('other.txt', b'other', method, password)
            + b'CLZ\x01' + bytes(12) + b'CLZ\x02')

def extra(sig, data, flags=0):
    return U32(sig) + bytes([flags]) + U16(len(data)) + data

def egg_header(identifier=1, prev=None, next=0, solid=False):
    return (b'EGGA' + U16(0x100) + U32(identifier) + bytes(4)
            + (extra(0x24F5A262, U32(prev) + U32(next)) if prev is not None else b'')
            + (extra(0x24E5A060, b'') if solid else b'') + END)

def egg_file(name, data, identifier, method=0, password=False, block_data=None, directory=False):
    actual = data if block_data is None else block_data
    packed = encode(method, actual)
    crc = zlib.crc32(actual)
    crypto = b''
    if password:
        cipher = encrypt(bytes(11) + bytes([crc >> 24]) + packed, '암호'.encode())
        crypto = extra(0x08D1470F, bytes([0]) + cipher[:12] + U32(crc))
        packed = cipher[12:]
    head = (U32(0x0A8590E3) + U32(identifier) + U64(len(data))
            + extra(0x0A8591AC, name.encode())
            + extra(0x2C86950B, bytes(8) + bytes([0x80 if directory else 0]))
            + crypto + END)
    if directory or block_data == b'':
        return head
    return head + U32(0x02B50C13) + bytes([method, 0]) + U32(len(actual)) + U32(len(packed)) + U32(crc) + END + packed

def egg(method=0, password=False, solid=False):
    return (egg_header(solid=solid)
            + egg_file('폴더/', b'', 1, directory=True)
            + egg_file('폴더/한글.txt', PAYLOAD, 2, method, password,
                       PAYLOAD + b'other' if solid else None)
            + egg_file('other.txt', b'other', 3, method, password, b'' if solid else None)
            + END)

for name, method in [('store',0),('deflate',2),('bzip2',1)]:
    (ROOT / f'{name}.alz').write_bytes(alz(method))
(ROOT / 'encrypted.alz').write_bytes(alz(2, True))
for name, method in [('store',0),('deflate',1),('bzip2',2),('azo-stored',3),('lzma',4)]:
    (ROOT / f'{name}.egg').write_bytes(egg(method))
(ROOT / 'encrypted.egg').write_bytes(egg(1, True))
(ROOT / 'solid.egg').write_bytes(egg(1, solid=True))
# Split in the compressed body, so readers must join payload across volumes.
a = alz(2)
cut = a.index(b'other.txt') - 15
(ROOT / 'split.alz').write_bytes(a[:cut] + bytes(16))
(ROOT / 'split.a00').write_bytes(b'ALZ\x01' + bytes(4) + a[cut:])
e = egg(1)
body = e[len(egg_header()):]
cut = body.index(b'other.txt') - 15
(ROOT / 'split.vol1.egg').write_bytes(egg_header(1, 0, 2) + body[:cut])
(ROOT / 'split.vol2.egg').write_bytes(egg_header(2, 1, 0) + body[cut:])
